import { TVariables } from "../types";

const getBackgroundStyles = (variables: TVariables) => `
  .q-bg-transparent { background-color: transparent; }
  .q-bg-body { background-color: ${variables["color.background.body"]}; }
  .q-bg-component { background-color: ${variables["color.background.component"]}; }
  .q-bg-opaque { background-color: ${variables["color.background.body"]}; }
  .q-bg-gray-1 { background-color: ${variables["color.gray.1"]}; }
  .q-bg-gray-2 { background-color: ${variables["color.gray.2"]}; }
  .q-bg-gray-3 { background-color: ${variables["color.gray.3"]}; }
  .q-bg-gray-4 { background-color: ${variables["color.gray.4"]}; }
  .q-bg-gray-5 { background-color: ${variables["color.gray.5"]}; }
  .q-bg-gray-6 { background-color: ${variables["color.gray.6"]}; }
  .q-bg-gray-7 { background-color: ${variables["color.gray.7"]}; }
  .q-bg-gray-8 { background-color: ${variables["color.gray.8"]}; }
  .q-bg-gray-9 { background-color: ${variables["color.gray.9"]}; }
  .q-bg-gray-10 { background-color: ${variables["color.gray.10"]}; }
  .q-bg-blue-1 { background-color: ${variables["color.blue.1"]}; }
  .q-bg-blue-2 { background-color: ${variables["color.blue.2"]}; }
  .q-bg-blue-3 { background-color: ${variables["color.blue.3"]}; }
  .q-bg-blue-4 { background-color: ${variables["color.blue.4"]}; }
  .q-bg-blue-5 { background-color: ${variables["color.blue.5"]}; }
  .q-bg-blue,.q-bg-blue-6 { background-color: ${variables["color.blue.6"]}; }
  .q-bg-blue-7 { background-color: ${variables["color.blue.7"]}; }
  .q-bg-blue-8 { background-color: ${variables["color.blue.8"]}; }
  .q-bg-blue-9 { background-color: ${variables["color.blue.9"]}; }
  .q-bg-blue-10 { background-color: ${variables["color.blue.10"]}; }
  .q-bg-green-1 { background-color: ${variables["color.green.1"]}; }
  .q-bg-green-2 { background-color: ${variables["color.green.2"]}; }
  .q-bg-green-3 { background-color: ${variables["color.green.3"]}; }
  .q-bg-green-4 { background-color: ${variables["color.green.4"]}; }
  .q-bg-green-5 { background-color: ${variables["color.green.5"]}; }
  .q-bg-green,.q-bg-green-6 { background-color: ${variables["color.green.6"]}; }
  .q-bg-green-7 { background-color: ${variables["color.green.7"]}; }
  .q-bg-green-8 { background-color: ${variables["color.green.8"]}; }
  .q-bg-green-9 { background-color: ${variables["color.green.9"]}; }
  .q-bg-green-10 { background-color: ${variables["color.green.10"]}; }
  .q-bg-cyan-1 { background-color: ${variables["color.cyan.1"]}; }
  .q-bg-cyan-2 { background-color: ${variables["color.cyan.2"]}; }
  .q-bg-cyan-3 { background-color: ${variables["color.cyan.3"]}; }
  .q-bg-cyan-4 { background-color: ${variables["color.cyan.4"]}; }
  .q-bg-cyan-5 { background-color: ${variables["color.cyan.5"]}; }
  .q-bg-cyan,.q-bg-cyan-6 { background-color: ${variables["color.cyan.6"]}; }
  .q-bg-cyan-7 { background-color: ${variables["color.cyan.7"]}; }
  .q-bg-cyan-8 { background-color: ${variables["color.cyan.8"]}; }
  .q-bg-cyan-9 { background-color: ${variables["color.cyan.9"]}; }
  .q-bg-cyan-10 { background-color: ${variables["color.cyan.10"]}; }
  .q-bg-yellow-1 { background-color: ${variables["color.yellow.1"]}; }
  .q-bg-yellow-2 { background-color: ${variables["color.yellow.2"]}; }
  .q-bg-yellow-3 { background-color: ${variables["color.yellow.3"]}; }
  .q-bg-yellow-4 { background-color: ${variables["color.yellow.4"]}; }
  .q-bg-yellow-5 { background-color: ${variables["color.yellow.5"]}; }
  .q-bg-yellow,.q-bg-yellow-6 { background-color: ${variables["color.yellow.6"]}; }
  .q-bg-yellow-7 { background-color: ${variables["color.yellow.7"]}; }
  .q-bg-yellow-8 { background-color: ${variables["color.yellow.8"]}; }
  .q-bg-yellow-9 { background-color: ${variables["color.yellow.9"]}; }
  .q-bg-yellow-10 { background-color: ${variables["color.yellow.10"]}; }
  .q-bg-orange-1 { background-color: ${variables["color.orange.1"]}; }
  .q-bg-orange-2 { background-color: ${variables["color.orange.2"]}; }
  .q-bg-orange-3 { background-color: ${variables["color.orange.3"]}; }
  .q-bg-orange-4 { background-color: ${variables["color.orange.4"]}; }
  .q-bg-orange-5 { background-color: ${variables["color.orange.5"]}; }
  .q-bg-orange,.q-bg-orange-6 { background-color: ${variables["color.orange.6"]}; }
  .q-bg-orange-7 { background-color: ${variables["color.orange.7"]}; }
  .q-bg-orange-8 { background-color: ${variables["color.orange.8"]}; }
  .q-bg-orange-9 { background-color: ${variables["color.orange.9"]}; }
  .q-bg-orange-10 { background-color: ${variables["color.orange.10"]}; }
  .q-bg-red-1 { background-color: ${variables["color.red.1"]}; }
  .q-bg-red-2 { background-color: ${variables["color.red.2"]}; }
  .q-bg-red-3 { background-color: ${variables["color.red.3"]}; }
  .q-bg-red-4 { background-color: ${variables["color.red.4"]}; }
  .q-bg-red-5 { background-color: ${variables["color.red.5"]}; }
  .q-bg-red,.q-bg-red-6 { background-color: ${variables["color.red.6"]}; }
  .q-bg-red-7 { background-color: ${variables["color.red.7"]}; }
  .q-bg-red-8 { background-color: ${variables["color.red.8"]}; }
  .q-bg-red-9 { background-color: ${variables["color.red.9"]}; }
  .q-bg-red-10 { background-color: ${variables["color.red.10"]}; }
  .q-bg-purple-1 { background-color: ${variables["color.purple.1"]}; }
  .q-bg-purple-2 { background-color: ${variables["color.purple.2"]}; }
  .q-bg-purple-3 { background-color: ${variables["color.purple.3"]}; }
  .q-bg-purple-4 { background-color: ${variables["color.purple.4"]}; }
  .q-bg-purple-5 { background-color: ${variables["color.purple.5"]}; }
  .q-bg-purple,.q-bg-purple-6 { background-color: ${variables["color.purple.6"]}; }
  .q-bg-purple-7 { background-color: ${variables["color.purple.7"]}; }
  .q-bg-purple-8 { background-color: ${variables["color.purple.8"]}; }
  .q-bg-purple-9 { background-color: ${variables["color.purple.9"]}; }
  .q-bg-purple-10 { background-color: ${variables["color.purple.10"]}; }
  .q-bg-pink-1 { background-color: ${variables["color.pink.1"]}; }
  .q-bg-pink-2 { background-color: ${variables["color.pink.2"]}; }
  .q-bg-pink-3 { background-color: ${variables["color.pink.3"]}; }
  .q-bg-pink-4 { background-color: ${variables["color.pink.4"]}; }
  .q-bg-pink-5 { background-color: ${variables["color.pink.5"]}; }
  .q-bg-pink,.q-bg-pink-6 { background-color: ${variables["color.pink.6"]}; }
  .q-bg-pink-7 { background-color: ${variables["color.pink.7"]}; }
  .q-bg-pink-8 { background-color: ${variables["color.pink.8"]}; }
  .q-bg-pink-9 { background-color: ${variables["color.pink.9"]}; }
  .q-bg-pink-10 { background-color: ${variables["color.pink.10"]}; }
  .q-bg-primary-1 { background-color: ${variables["color.primary.1"]}; }
  .q-bg-primary-2 { background-color: ${variables["color.primary.2"]}; }
  .q-bg-primary-3 { background-color: ${variables["color.primary.3"]}; }
  .q-bg-primary-4 { background-color: ${variables["color.primary.4"]}; }
  .q-bg-primary-5 { background-color: ${variables["color.primary.5"]}; }
  .q-bg-primary-6 { background-color: ${variables["color.primary.6"]}; }
  .q-bg-primary-7 { background-color: ${variables["color.primary.7"]}; }
  .q-bg-primary-8 { background-color: ${variables["color.primary.8"]}; }
  .q-bg-primary-9 { background-color: ${variables["color.primary.9"]}; }
  .q-bg-primary-10 { background-color: ${variables["color.primary.10"]}; }
  .q-bg-success-1 { background-color: ${variables["color.success.1"]}; }
  .q-bg-success-2 { background-color: ${variables["color.success.2"]}; }
  .q-bg-success-3 { background-color: ${variables["color.success.3"]}; }
  .q-bg-success-4 { background-color: ${variables["color.success.4"]}; }
  .q-bg-success-5 { background-color: ${variables["color.success.5"]}; }
  .q-bg-success-6 { background-color: ${variables["color.success.6"]}; }
  .q-bg-success-7 { background-color: ${variables["color.success.7"]}; }
  .q-bg-success-8 { background-color: ${variables["color.success.8"]}; }
  .q-bg-success-9 { background-color: ${variables["color.success.9"]}; }
  .q-bg-success-10 { background-color: ${variables["color.success.10"]}; }
  .q-bg-info-1 { background-color: ${variables["color.info.1"]}; }
  .q-bg-info-2 { background-color: ${variables["color.info.2"]}; }
  .q-bg-info-3 { background-color: ${variables["color.info.3"]}; }
  .q-bg-info-4 { background-color: ${variables["color.info.4"]}; }
  .q-bg-info-5 { background-color: ${variables["color.info.5"]}; }
  .q-bg-info-6 { background-color: ${variables["color.info.6"]}; }
  .q-bg-info-7 { background-color: ${variables["color.info.7"]}; }
  .q-bg-info-8 { background-color: ${variables["color.info.8"]}; }
  .q-bg-info-9 { background-color: ${variables["color.info.9"]}; }
  .q-bg-info-10 { background-color: ${variables["color.info.10"]}; }
  .q-bg-warning-1 { background-color: ${variables["color.warning.1"]}; }
  .q-bg-warning-2 { background-color: ${variables["color.warning.2"]}; }
  .q-bg-warning-3 { background-color: ${variables["color.warning.3"]}; }
  .q-bg-warning-4 { background-color: ${variables["color.warning.4"]}; }
  .q-bg-warning-5 { background-color: ${variables["color.warning.5"]}; }
  .q-bg-warning-6 { background-color: ${variables["color.warning.6"]}; }
  .q-bg-warning-7 { background-color: ${variables["color.warning.7"]}; }
  .q-bg-warning-8 { background-color: ${variables["color.warning.8"]}; }
  .q-bg-warning-9 { background-color: ${variables["color.warning.9"]}; }
  .q-bg-warning-10 { background-color: ${variables["color.warning.10"]}; }
  .q-bg-danger-1,.q-bg-error-1 { background-color: ${variables["color.error.1"]}; }
  .q-bg-danger-2,.q-bg-error-2 { background-color: ${variables["color.error.2"]}; }
  .q-bg-danger-3,.q-bg-error-3 { background-color: ${variables["color.error.3"]}; }
  .q-bg-danger-4,.q-bg-error-4 { background-color: ${variables["color.error.4"]}; }
  .q-bg-danger-5,.q-bg-error-5 { background-color: ${variables["color.error.5"]}; }
  .q-bg-danger-6,.q-bg-error-6 { background-color: ${variables["color.error.6"]}; }
  .q-bg-danger-7,.q-bg-error-7 { background-color: ${variables["color.error.7"]}; }
  .q-bg-danger-8,.q-bg-error-8 { background-color: ${variables["color.error.8"]}; }
  .q-bg-danger-9,.q-bg-error-9 { background-color: ${variables["color.error.9"]}; }
  .q-bg-danger-10,.q-bg-error-10 { background-color: ${variables["color.error.10"]}; }
  .q-bg-primary { background-color: ${variables["color.primary"]}; }
  .q-bg-success { background-color: ${variables["color.success"]}; }
  .q-bg-info { background-color: ${variables["color.info"]}; }
  .q-bg-warning { background-color: ${variables["color.warning"]}; }
  .q-bg-danger,.q-bg-error { background-color: ${variables["color.error"]}; }
  .q-bg-white { background-color: ${variables["color.white"]}; }
`;

export default getBackgroundStyles;
