import { TVariables } from "../types";

const getColorStyles = (variables: TVariables) => `
  .q-color-default { color: ${variables["font.color"]}; }
  .q-color-secondary { color: ${variables["font.color.secondary"]}; }
  .q-gray-1 { color: ${variables["color.gray.1"]}; }
  .q-gray-2 { color: ${variables["color.gray.2"]}; }
  .q-gray-3 { color: ${variables["color.gray.3"]}; }
  .q-gray-4 { color: ${variables["color.gray.4"]}; }
  .q-gray-5 { color: ${variables["color.gray.5"]}; }
  .q-gray-6 { color: ${variables["color.gray.6"]}; }
  .q-gray-7 { color: ${variables["color.gray.7"]}; }
  .q-gray-8 { color: ${variables["color.gray.8"]}; }
  .q-gray-9 { color: ${variables["color.gray.9"]}; }
  .q-gray-10 { color: ${variables["color.gray.10"]}; }
  .q-blue-1 { color: ${variables["color.blue.1"]}; }
  .q-blue-2 { color: ${variables["color.blue.2"]}; }
  .q-blue-3 { color: ${variables["color.blue.3"]}; }
  .q-blue-4 { color: ${variables["color.blue.4"]}; }
  .q-blue-5 { color: ${variables["color.blue.5"]}; }
  .q-blue,.q-blue-6 { color: ${variables["color.blue.6"]}; }
  .q-blue-7 { color: ${variables["color.blue.7"]}; }
  .q-blue-8 { color: ${variables["color.blue.8"]}; }
  .q-blue-9 { color: ${variables["color.blue.9"]}; }
  .q-blue-10 { color: ${variables["color.blue.10"]}; }
  .q-green-1 { color: ${variables["color.green.1"]}; }
  .q-green-2 { color: ${variables["color.green.2"]}; }
  .q-green-3 { color: ${variables["color.green.3"]}; }
  .q-green-4 { color: ${variables["color.green.4"]}; }
  .q-green-5 { color: ${variables["color.green.5"]}; }
  .q-green,.q-green-6 { color: ${variables["color.green.6"]}; }
  .q-green-7 { color: ${variables["color.green.7"]}; }
  .q-green-8 { color: ${variables["color.green.8"]}; }
  .q-green-9 { color: ${variables["color.green.9"]}; }
  .q-green-10 { color: ${variables["color.green.10"]}; }
  .q-cyan-1 { color: ${variables["color.cyan.1"]}; }
  .q-cyan-2 { color: ${variables["color.cyan.2"]}; }
  .q-cyan-3 { color: ${variables["color.cyan.3"]}; }
  .q-cyan-4 { color: ${variables["color.cyan.4"]}; }
  .q-cyan-5 { color: ${variables["color.cyan.5"]}; }
  .q-cyan,.q-cyan-6 { color: ${variables["color.cyan.6"]}; }
  .q-cyan-7 { color: ${variables["color.cyan.7"]}; }
  .q-cyan-8 { color: ${variables["color.cyan.8"]}; }
  .q-cyan-9 { color: ${variables["color.cyan.9"]}; }
  .q-cyan-10 { color: ${variables["color.cyan.10"]}; }
  .q-yellow-1 { color: ${variables["color.yellow.1"]}; }
  .q-yellow-2 { color: ${variables["color.yellow.2"]}; }
  .q-yellow-3 { color: ${variables["color.yellow.3"]}; }
  .q-yellow-4 { color: ${variables["color.yellow.4"]}; }
  .q-yellow-5 { color: ${variables["color.yellow.5"]}; }
  .q-yellow,.q-yellow-6 { color: ${variables["color.yellow.6"]}; }
  .q-yellow-7 { color: ${variables["color.yellow.7"]}; }
  .q-yellow-8 { color: ${variables["color.yellow.8"]}; }
  .q-yellow-9 { color: ${variables["color.yellow.9"]}; }
  .q-yellow-10 { color: ${variables["color.yellow.10"]}; }
  .q-orange-1 { color: ${variables["color.orange.1"]}; }
  .q-orange-2 { color: ${variables["color.orange.2"]}; }
  .q-orange-3 { color: ${variables["color.orange.3"]}; }
  .q-orange-4 { color: ${variables["color.orange.4"]}; }
  .q-orange-5 { color: ${variables["color.orange.5"]}; }
  .q-orange,.q-orange-6 { color: ${variables["color.orange.6"]}; }
  .q-orange-7 { color: ${variables["color.orange.7"]}; }
  .q-orange-8 { color: ${variables["color.orange.8"]}; }
  .q-orange-9 { color: ${variables["color.orange.9"]}; }
  .q-orange-10 { color: ${variables["color.orange.10"]}; }
  .q-red-1 { color: ${variables["color.red.1"]}; }
  .q-red-2 { color: ${variables["color.red.2"]}; }
  .q-red-3 { color: ${variables["color.red.3"]}; }
  .q-red-4 { color: ${variables["color.red.4"]}; }
  .q-red-5 { color: ${variables["color.red.5"]}; }
  .q-red,.q-red-6 { color: ${variables["color.red.6"]}; }
  .q-red-7 { color: ${variables["color.red.7"]}; }
  .q-red-8 { color: ${variables["color.red.8"]}; }
  .q-red-9 { color: ${variables["color.red.9"]}; }
  .q-red-10 { color: ${variables["color.red.10"]}; }
  .q-purple-1 { color: ${variables["color.purple.1"]}; }
  .q-purple-2 { color: ${variables["color.purple.2"]}; }
  .q-purple-3 { color: ${variables["color.purple.3"]}; }
  .q-purple-4 { color: ${variables["color.purple.4"]}; }
  .q-purple-5 { color: ${variables["color.purple.5"]}; }
  .q-purple,.q-purple-6 { color: ${variables["color.purple.6"]}; }
  .q-purple-7 { color: ${variables["color.purple.7"]}; }
  .q-purple-8 { color: ${variables["color.purple.8"]}; }
  .q-purple-9 { color: ${variables["color.purple.9"]}; }
  .q-purple-10 { color: ${variables["color.purple.10"]}; }
  .q-pink-1 { color: ${variables["color.pink.1"]}; }
  .q-pink-2 { color: ${variables["color.pink.2"]}; }
  .q-pink-3 { color: ${variables["color.pink.3"]}; }
  .q-pink-4 { color: ${variables["color.pink.4"]}; }
  .q-pink-5 { color: ${variables["color.pink.5"]}; }
  .q-pink,.q-pink-6 { color: ${variables["color.pink.6"]}; }
  .q-pink-7 { color: ${variables["color.pink.7"]}; }
  .q-pink-8 { color: ${variables["color.pink.8"]}; }
  .q-pink-9 { color: ${variables["color.pink.9"]}; }
  .q-pink-10 { color: ${variables["color.pink.10"]}; }
  .q-primary-1 { color: ${variables["color.primary.1"]}; }
  .q-primary-2 { color: ${variables["color.primary.2"]}; }
  .q-primary-3 { color: ${variables["color.primary.3"]}; }
  .q-primary-4 { color: ${variables["color.primary.4"]}; }
  .q-primary-5 { color: ${variables["color.primary.5"]}; }
  .q-primary-6 { color: ${variables["color.primary.6"]}; }
  .q-primary-7 { color: ${variables["color.primary.7"]}; }
  .q-primary-8 { color: ${variables["color.primary.8"]}; }
  .q-primary-9 { color: ${variables["color.primary.9"]}; }
  .q-primary-10 { color: ${variables["color.primary.10"]}; }
  .q-success-1 { color: ${variables["color.success.1"]}; }
  .q-success-2 { color: ${variables["color.success.2"]}; }
  .q-success-3 { color: ${variables["color.success.3"]}; }
  .q-success-4 { color: ${variables["color.success.4"]}; }
  .q-success-5 { color: ${variables["color.success.5"]}; }
  .q-success-6 { color: ${variables["color.success.6"]}; }
  .q-success-7 { color: ${variables["color.success.7"]}; }
  .q-success-8 { color: ${variables["color.success.8"]}; }
  .q-success-9 { color: ${variables["color.success.9"]}; }
  .q-success-10 { color: ${variables["color.success.10"]}; }
  .q-info-1 { color: ${variables["color.info.1"]}; }
  .q-info-2 { color: ${variables["color.info.2"]}; }
  .q-info-3 { color: ${variables["color.info.3"]}; }
  .q-info-4 { color: ${variables["color.info.4"]}; }
  .q-info-5 { color: ${variables["color.info.5"]}; }
  .q-info-6 { color: ${variables["color.info.6"]}; }
  .q-info-7 { color: ${variables["color.info.7"]}; }
  .q-info-8 { color: ${variables["color.info.8"]}; }
  .q-info-9 { color: ${variables["color.info.9"]}; }
  .q-info-10 { color: ${variables["color.info.10"]}; }
  .q-warning-1 { color: ${variables["color.warning.1"]}; }
  .q-warning-2 { color: ${variables["color.warning.2"]}; }
  .q-warning-3 { color: ${variables["color.warning.3"]}; }
  .q-warning-4 { color: ${variables["color.warning.4"]}; }
  .q-warning-5 { color: ${variables["color.warning.5"]}; }
  .q-warning-6 { color: ${variables["color.warning.6"]}; }
  .q-warning-7 { color: ${variables["color.warning.7"]}; }
  .q-warning-8 { color: ${variables["color.warning.8"]}; }
  .q-warning-9 { color: ${variables["color.warning.9"]}; }
  .q-warning-10 { color: ${variables["color.warning.10"]}; }
  .q-danger-1,.q-error-1 { color: ${variables["color.error.1"]}; }
  .q-danger-2,.q-error-2 { color: ${variables["color.error.2"]}; }
  .q-danger-3,.q-error-3 { color: ${variables["color.error.3"]}; }
  .q-danger-4,.q-error-4 { color: ${variables["color.error.4"]}; }
  .q-danger-5,.q-error-5 { color: ${variables["color.error.5"]}; }
  .q-danger-6,.q-error-6 { color: ${variables["color.error.6"]}; }
  .q-danger-7,.q-error-7 { color: ${variables["color.error.7"]}; }
  .q-danger-8,.q-error-8 { color: ${variables["color.error.8"]}; }
  .q-danger-9,.q-error-9 { color: ${variables["color.error.9"]}; }
  .q-danger-10,.q-error-10 { color: ${variables["color.error.10"]}; }
  .q-primary { color: ${variables["color.primary"]}; }
  .q-success { color: ${variables["color.success"]}; }
  .q-info { color: ${variables["color.info"]}; }
  .q-warning { color: ${variables["color.warning"]}; }
  .q-danger,.q-error { color: ${variables["color.error"]}; }
  .q-white { color: ${variables["color.white"]}; }
`;

export default getColorStyles;
