import { TVariables } from "../types";

const getBorderStyles = (variables: TVariables) => `
  .q-border { border: solid 1px ${variables["border.color"]}; }
  .q-border-l { border-left: solid 1px ${variables["border.color"]}; }
  .q-border-r { border-right: solid 1px ${variables["border.color"]}; }
  .q-border-t { border-top: solid 1px ${variables["border.color"]}; }
  .q-border-b { border-bottom: solid 1px ${variables["border.color"]}; }
  .q-border-secondary { border-color: ${variables["border.color.secondary"]}; }
  .q-border-gray-1 { border-color: ${variables["color.gray.1"]}; }
  .q-border-gray-2 { border-color: ${variables["color.gray.2"]}; }
  .q-border-gray-3 { border-color: ${variables["color.gray.3"]}; }
  .q-border-gray-4 { border-color: ${variables["color.gray.4"]}; }
  .q-border-gray-5 { border-color: ${variables["color.gray.5"]}; }
  .q-border-gray-6 { border-color: ${variables["color.gray.6"]}; }
  .q-border-gray-7 { border-color: ${variables["color.gray.7"]}; }
  .q-border-gray-8 { border-color: ${variables["color.gray.8"]}; }
  .q-border-gray-9 { border-color: ${variables["color.gray.9"]}; }
  .q-border-gray-10 { border-color: ${variables["color.gray.10"]}; }
  .q-border-blue-1 { border-color: ${variables["color.blue.1"]}; }
  .q-border-blue-2 { border-color: ${variables["color.blue.2"]}; }
  .q-border-blue-3 { border-color: ${variables["color.blue.3"]}; }
  .q-border-blue-4 { border-color: ${variables["color.blue.4"]}; }
  .q-border-blue-5 { border-color: ${variables["color.blue.5"]}; }
  .q-border-blue,.q-border-blue-6 { border-color: ${variables["color.blue.6"]}; }
  .q-border-blue-7 { border-color: ${variables["color.blue.7"]}; }
  .q-border-blue-8 { border-color: ${variables["color.blue.8"]}; }
  .q-border-blue-9 { border-color: ${variables["color.blue.9"]}; }
  .q-border-blue-10 { border-color: ${variables["color.blue.10"]}; }
  .q-border-green-1 { border-color: ${variables["color.green.1"]}; }
  .q-border-green-2 { border-color: ${variables["color.green.2"]}; }
  .q-border-green-3 { border-color: ${variables["color.green.3"]}; }
  .q-border-green-4 { border-color: ${variables["color.green.4"]}; }
  .q-border-green-5 { border-color: ${variables["color.green.5"]}; }
  .q-border-green,.q-border-green-6 { border-color: ${variables["color.green.6"]}; }
  .q-border-green-7 { border-color: ${variables["color.green.7"]}; }
  .q-border-green-8 { border-color: ${variables["color.green.8"]}; }
  .q-border-green-9 { border-color: ${variables["color.green.9"]}; }
  .q-border-green-10 { border-color: ${variables["color.green.10"]}; }
  .q-border-cyan-1 { border-color: ${variables["color.cyan.1"]}; }
  .q-border-cyan-2 { border-color: ${variables["color.cyan.2"]}; }
  .q-border-cyan-3 { border-color: ${variables["color.cyan.3"]}; }
  .q-border-cyan-4 { border-color: ${variables["color.cyan.4"]}; }
  .q-border-cyan-5 { border-color: ${variables["color.cyan.5"]}; }
  .q-border-cyan,.q-border-cyan-6 { border-color: ${variables["color.cyan.6"]}; }
  .q-border-cyan-7 { border-color: ${variables["color.cyan.7"]}; }
  .q-border-cyan-8 { border-color: ${variables["color.cyan.8"]}; }
  .q-border-cyan-9 { border-color: ${variables["color.cyan.9"]}; }
  .q-border-cyan-10 { border-color: ${variables["color.cyan.10"]}; }
  .q-border-yellow-1 { border-color: ${variables["color.yellow.1"]}; }
  .q-border-yellow-2 { border-color: ${variables["color.yellow.2"]}; }
  .q-border-yellow-3 { border-color: ${variables["color.yellow.3"]}; }
  .q-border-yellow-4 { border-color: ${variables["color.yellow.4"]}; }
  .q-border-yellow-5 { border-color: ${variables["color.yellow.5"]}; }
  .q-border-yellow,.q-border-yellow-6 { border-color: ${variables["color.yellow.6"]}; }
  .q-border-yellow-7 { border-color: ${variables["color.yellow.7"]}; }
  .q-border-yellow-8 { border-color: ${variables["color.yellow.8"]}; }
  .q-border-yellow-9 { border-color: ${variables["color.yellow.9"]}; }
  .q-border-yellow-10 { border-color: ${variables["color.yellow.10"]}; }
  .q-border-orange-1 { border-color: ${variables["color.orange.1"]}; }
  .q-border-orange-2 { border-color: ${variables["color.orange.2"]}; }
  .q-border-orange-3 { border-color: ${variables["color.orange.3"]}; }
  .q-border-orange-4 { border-color: ${variables["color.orange.4"]}; }
  .q-border-orange-5 { border-color: ${variables["color.orange.5"]}; }
  .q-border-orange,.q-border-orange-6 { border-color: ${variables["color.orange.6"]}; }
  .q-border-orange-7 { border-color: ${variables["color.orange.7"]}; }
  .q-border-orange-8 { border-color: ${variables["color.orange.8"]}; }
  .q-border-orange-9 { border-color: ${variables["color.orange.9"]}; }
  .q-border-orange-10 { border-color: ${variables["color.orange.10"]}; }
  .q-border-red-1 { border-color: ${variables["color.red.1"]}; }
  .q-border-red-2 { border-color: ${variables["color.red.2"]}; }
  .q-border-red-3 { border-color: ${variables["color.red.3"]}; }
  .q-border-red-4 { border-color: ${variables["color.red.4"]}; }
  .q-border-red-5 { border-color: ${variables["color.red.5"]}; }
  .q-border-red,.q-border-red-6 { border-color: ${variables["color.red.6"]}; }
  .q-border-red-7 { border-color: ${variables["color.red.7"]}; }
  .q-border-red-8 { border-color: ${variables["color.red.8"]}; }
  .q-border-red-9 { border-color: ${variables["color.red.9"]}; }
  .q-border-red-10 { border-color: ${variables["color.red.10"]}; }
  .q-border-purple-1 { border-color: ${variables["color.purple.1"]}; }
  .q-border-purple-2 { border-color: ${variables["color.purple.2"]}; }
  .q-border-purple-3 { border-color: ${variables["color.purple.3"]}; }
  .q-border-purple-4 { border-color: ${variables["color.purple.4"]}; }
  .q-border-purple-5 { border-color: ${variables["color.purple.5"]}; }
  .q-border-purple,.q-border-purple-6 { border-color: ${variables["color.purple.6"]}; }
  .q-border-purple-7 { border-color: ${variables["color.purple.7"]}; }
  .q-border-purple-8 { border-color: ${variables["color.purple.8"]}; }
  .q-border-purple-9 { border-color: ${variables["color.purple.9"]}; }
  .q-border-purple-10 { border-color: ${variables["color.purple.10"]}; }
  .q-border-pink-1 { border-color: ${variables["color.pink.1"]}; }
  .q-border-pink-2 { border-color: ${variables["color.pink.2"]}; }
  .q-border-pink-3 { border-color: ${variables["color.pink.3"]}; }
  .q-border-pink-4 { border-color: ${variables["color.pink.4"]}; }
  .q-border-pink-5 { border-color: ${variables["color.pink.5"]}; }
  .q-border-pink,.q-border-pink-6 { border-color: ${variables["color.pink.6"]}; }
  .q-border-pink-7 { border-color: ${variables["color.pink.7"]}; }
  .q-border-pink-8 { border-color: ${variables["color.pink.8"]}; }
  .q-border-pink-9 { border-color: ${variables["color.pink.9"]}; }
  .q-border-pink-10 { border-color: ${variables["color.pink.10"]}; }
  .q-border-primary-1 { border-color: ${variables["color.primary.1"]}; }
  .q-border-primary-2 { border-color: ${variables["color.primary.2"]}; }
  .q-border-primary-3 { border-color: ${variables["color.primary.3"]}; }
  .q-border-primary-4 { border-color: ${variables["color.primary.4"]}; }
  .q-border-primary-5 { border-color: ${variables["color.primary.5"]}; }
  .q-border-primary-6 { border-color: ${variables["color.primary.6"]}; }
  .q-border-primary-7 { border-color: ${variables["color.primary.7"]}; }
  .q-border-primary-8 { border-color: ${variables["color.primary.8"]}; }
  .q-border-primary-9 { border-color: ${variables["color.primary.9"]}; }
  .q-border-primary-10 { border-color: ${variables["color.primary.10"]}; }
  .q-border-success-1 { border-color: ${variables["color.success.1"]}; }
  .q-border-success-2 { border-color: ${variables["color.success.2"]}; }
  .q-border-success-3 { border-color: ${variables["color.success.3"]}; }
  .q-border-success-4 { border-color: ${variables["color.success.4"]}; }
  .q-border-success-5 { border-color: ${variables["color.success.5"]}; }
  .q-border-success-6 { border-color: ${variables["color.success.6"]}; }
  .q-border-success-7 { border-color: ${variables["color.success.7"]}; }
  .q-border-success-8 { border-color: ${variables["color.success.8"]}; }
  .q-border-success-9 { border-color: ${variables["color.success.9"]}; }
  .q-border-success-10 { border-color: ${variables["color.success.10"]}; }
  .q-border-info-1 { border-color: ${variables["color.info.1"]}; }
  .q-border-info-2 { border-color: ${variables["color.info.2"]}; }
  .q-border-info-3 { border-color: ${variables["color.info.3"]}; }
  .q-border-info-4 { border-color: ${variables["color.info.4"]}; }
  .q-border-info-5 { border-color: ${variables["color.info.5"]}; }
  .q-border-info-6 { border-color: ${variables["color.info.6"]}; }
  .q-border-info-7 { border-color: ${variables["color.info.7"]}; }
  .q-border-info-8 { border-color: ${variables["color.info.8"]}; }
  .q-border-info-9 { border-color: ${variables["color.info.9"]}; }
  .q-border-info-10 { border-color: ${variables["color.info.10"]}; }
  .q-border-warning-1 { border-color: ${variables["color.warning.1"]}; }
  .q-border-warning-2 { border-color: ${variables["color.warning.2"]}; }
  .q-border-warning-3 { border-color: ${variables["color.warning.3"]}; }
  .q-border-warning-4 { border-color: ${variables["color.warning.4"]}; }
  .q-border-warning-5 { border-color: ${variables["color.warning.5"]}; }
  .q-border-warning-6 { border-color: ${variables["color.warning.6"]}; }
  .q-border-warning-7 { border-color: ${variables["color.warning.7"]}; }
  .q-border-warning-8 { border-color: ${variables["color.warning.8"]}; }
  .q-border-warning-9 { border-color: ${variables["color.warning.9"]}; }
  .q-border-warning-10 { border-color: ${variables["color.warning.10"]}; }
  .q-border-danger-1,.q-border-error-1 { border-color: ${variables["color.error.1"]}; }
  .q-border-danger-2,.q-border-error-2 { border-color: ${variables["color.error.2"]}; }
  .q-border-danger-3,.q-border-error-3 { border-color: ${variables["color.error.3"]}; }
  .q-border-danger-4,.q-border-error-4 { border-color: ${variables["color.error.4"]}; }
  .q-border-danger-5,.q-border-error-5 { border-color: ${variables["color.error.5"]}; }
  .q-border-danger-6,.q-border-error-6 { border-color: ${variables["color.error.6"]}; }
  .q-border-danger-7,.q-border-error-7 { border-color: ${variables["color.error.7"]}; }
  .q-border-danger-8,.q-border-error-8 { border-color: ${variables["color.error.8"]}; }
  .q-border-danger-9,.q-border-error-9 { border-color: ${variables["color.error.9"]}; }
  .q-border-danger-10,.q-border-error-10 { border-color: ${variables["color.error.10"]}; }
  .q-border-primary { border-color: ${variables["color.primary"]}; }
  .q-border-success { border-color: ${variables["color.success"]}; }
  .q-border-info { border-color: ${variables["color.info"]}; }
  .q-border-warning { border-color: ${variables["color.warning"]}; }
  .q-border-danger,.q-border-error { border-color: ${variables["color.error"]}; }
`;

export default getBorderStyles;
